container:
  image: quay.io/droidian/build-essential:bookworm-amd64
  cpu: 8
  memory: 32G
env:
  GITHUB_TOKEN: ENCRYPTED[b28f79174c63e23e95a6767888d6b64b4c377572a2a4ee842cc115cce0e2d9f4dc6a655053bea7928630ae64dbefffee]
  PACKAGES_DIR: "droidian/packages"
  KERNEL_DIR: "droidian/kernel/xiaomi/rosy"

build_task:
  preparation_script:
    - mkdir -p droidian/{packages/buildd,kernel/xiaomi/rosy}/
    - git clone https://github.com/droidian/linux-packaging-snippets.git
    - git clone https://github.com/neizhmak/droidian_kernel_xiaomi_rosy.git -b bookworm $KERNEL_DIR
    - mkdir -p $KERNEL_DIR/buildd/sources/debian/source
    - cp kernel-info.mk $KERNEL_DIR/buildd/sources/debian/
    - echo 13 >> $KERNEL_DIR/buildd/sources/debian/compat
    - echo "3.0 (native)" >> $KERNEL_DIR/buildd/sources/debian/source/format
    - cp rules $KERNEL_DIR/buildd/sources/debian/
    - chmod +x $KERNEL_DIR/buildd/sources/debian/rules
  build_script:
    - cd $KERNEL_DIR/buildd/sources 
    - debian/rules debian/control
    - RELENG_HOST_ARCH="arm64" releng-build-package
  publish_release_script: source ../publish_release.sh
