container:
  image: quay.io/droidian/build-essential:bookworm-amd64
  cpu: 8
  memory: 32G
env:
  GITHUB_TOKEN: ENCRYPTED[5b012b7356926cedbafd1f9b5ff12bcaf36cc741196f0d5e7df4cf12d41e02c9bc60faa9275aa4c6afef8472e92a5aff]
  PACKAGES_DIR: "/tmp/cirrus-ci-build/packages"
  KERNEL_DIR: "/tmp/cirrus-ci-build/android_kernel_xiaomi_rosy"
  FILES_DIR: "/tmp/cirrus-ci-build/"
  PATH: "$PATH:/usr/lib/llvm-android-10.0-r370808/bin"
  CI: ""

build_task:
  preparation_script:
    - git clone https://github.com/baunilla/android_kernel_xiaomi_rosy.git -b lineage-18.1
    - mkdir -p packages/buildd
    - cd $KERNEL_DIR
    - git checkout -b bookworm
    - cp $FILES_DIR/rosy-perf-halium_defconfig arch/arm64/configs/
    - mkdir -p debian/source out/KERNEL_OBJ
    - cd debian 
    - echo "3.0 (native)" >> source/format
    - echo >> /.dockerenv
    - echo 13 >> compat 
    - cp $FILES_DIR/kernel-info.mk ./
    - cp $FILES_DIR/rules ./
    - chmod +x rules
    - apt update -y
    - apt install -y linux-packaging-snippets clang-android-10.0-r370808 python
    - clang -v
  build_script:
    - cd $KERNEL_DIR
    - debian/rules debian/control
    - RELENG_HOST_ARCH=arm64 releng-build-package
  publish_release_script: source publish_release.sh
