container:
  image: archlinux:latest
  cpu: 8
  memory: 32G

build_task:
  preparation_script:
    - echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
    - pacman -Suy --noconfirm base-devel git sudo 
    - useradd -m -g users -s /bin/bash user
    - echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    - git clone https://aur.archlinux.org/yay-bin.git
    - chmod 777 yay-bin
    - cd yay-bin
    - su user -c "makepkg --noconfirm -si"
    - su user -c "yay -S --noconfirm halium-devel"
    - cd ../
    - mkdir python2
    - python -m venv python2
    - source python2/bin/activate
    - mkdir halium 
  get_source_script:
    - cd halium
    - git config --global user.name  "Artem Neizhmak"
    - git config --global user.email "ytartem0007@gmail.com"
    - repo init -u https://github.com/Halium/android -b halium-11.0 --depth=1 --git-lfs
    - repo sync -c -j 16
    - cp ../xiaomi_rosy.xml halium/devices/manifests/
    - ./halium/devices/setup rosy
  build_script:
    - cd halium
    - source build/envsetup.sh
    - breakfast rosy
    - cp ../rosy-perf_defconfig kernel/xiaomi/rosy/arch/arm64/configs/rosy-perf_defconfig
    - hybris-patches/apply-patches.sh --mb
    - mka mkbootimg
    - export USE_HOST_LEX=yes
    - mka halium-boot
    - mka systemimage
  env:
    GITHUB_TOKEN: ENCRYPTED[13a5662b449c90997bc914dc49c7c5fab2ed763cfdedda700cbb8372e4d8844e7b1a3044928d67888bcbb71aac0ad2f6]
  publish_release_script:
    - source ../publish_release.sh
