container:
  image: quay.io/droidian/build-essential:bookworm-amd64
  cpu: 8
  memory: 32G
env:
  GITHUB_TOKEN: ENCRYPTED[b28f79174c63e23e95a6767888d6b64b4c377572a2a4ee842cc115cce0e2d9f4dc6a655053bea7928630ae64dbefffee]
  PACKAGES_DIR: "$HOME/droidian/packages"
  KERNEL_DIR: "$HOME/droidian/kernel/vendor/device"

build_task:
  preparation_script:
    - mkdir -p droidian/{packages/buildd,kernel/vendor/device}/
    - git clone https://github.com/baunilla/android_kernel_xiaomi_rosy.git -b lineage-18.1 $KERNEL_DIR
    - cd $KERNEL_DIR
    - git checkout -b bookworm
    - cp ~/rosy-perf-halium_defconfig arch/arm64/configs/
    - mkdir -p buildd/sources/debian/source
    - apt install -y linux-packaging-snippets
    - cp kernel-info.mk buildd/sources/debian/
    - echo 13 >> buildd/sources/debian/compat
    - echo "3.0 (native)" >> buildd/sources/debian/source/format
    - cp rules buildd/sources/debian/
    - chmod +x buildd/sources/debian/rules
  build_script:
    - cd $KERNEL_DIR/buildd/sources
    - debian/rules debian/control
    - RELENG_HOST_ARCH="arm64" releng-build-package
  publish_release_script: source ../publish_release.sh
