container:
  image: quay.io/droidian/build-essential:bookworm-amd64
  cpu: 8
  memory: 32G
env:
  KERNEL_SOURCE: "https://github.com/baunilla/android_kernel_xiaomi_rosy.git -b lineage-18.1"
  GITHUB_TOKEN: ENCRYPTED[5b012b7356926cedbafd1f9b5ff12bcaf36cc741196f0d5e7df4cf12d41e02c9bc60faa9275aa4c6afef8472e92a5aff]
  PACKAGES_DIR: "/tmp/cirrus-ci-build/packages"
  KERNEL_DIR: "/tmp/cirrus-ci-build/android_kernel_xiaomi_rosy"
  HOME: "/tmp/cirrus-ci-build/"
  LANG: "C"
  CI: ""
  q: ">/dev/null"

build_task:
  preparation_script:
    - $q git clone $KERNEL_SOURCE
    - cd $KERNEL_DIR
    - cp ~/*defconfig arch/arm64/configs/
    - mkdir -p debian/source
    - cd debian
    - echo 13 >> compat
    - echo >> /.dockerenv
    - echo "3.0 (native)" >> source/format
    - cp ~/{kernel-info.mk,rules} ./
    - chmod +x rules ~/publish_release.sh
    - $q apt update -y
    - $q apt install -y linux-packaging-snippets curl
    - sed -i "256iln -s /usr/lib/llvm-android-*/bin/* /bin/" /bin/releng-build-package
  build_script:
    - cd $KERNEL_DIR
    - $q debian/rules debian/control
    - $q RELENG_HOST_ARCH=arm64 releng-build-package
  publish_release_script: ./publish_release.sh
