container:
  image: quay.io/droidian/build-essential:bookworm-amd64
  cpu: 8
  memory: 32G

build_task:
  preparation_script:
    - mkdir -p droidian/{packages/buildd,
        kernel/vendor/device/buildd/sources/debian/source}
    - KERNEL_DIR="$HOME/droidian/kernel/vendor/device"
    - PACKAGES_DIR="$HOME/droidian/packages"
    - echo 13 > $KERNEL_DIR:/buildd/sources/debian/debian/compat
    - echo "3.0 (native)" > $KERNEL_DIR:/buildd/sources/debian/source/format
    - cp rules $KERNEL_DIR:/buildd/sources/debian/
    - chmod +x $KERNEL_DIR:/buildd/sources/debian/rules
    - git clone https://github.com/neizhmak/droidian_kernel_xiaomi_rosy.git -b bookworm $KERNEL_DIR
  get_source_script:
    - apt install linux-packaging-snippets
    - cat /usr/share/linux-packaging-snippets/kernel-info.mk.example
    - unpackbootimg --boot_img boot.img
    - ls
  build_script:
    - exit
  env:
    GITHUB_TOKEN: ENCRYPTED[13a5662b449c90997bc914dc49c7c5fab2ed763cfdedda700cbb8372e4d8844e7b1a3044928d67888bcbb71aac0ad2f6]
  publish_release_script:
    - source ../publish_release.sh
