container:
  image: debian:latest
  cpu: 8
  memory: 32G

build_task:
  preparation_script:
    - dpkg --add-architecture i386
    - apt update -y
    - apt upgrade -y
    - cat /etc/apt/sources.list
    - apt install git gnupg flex bison gperf build-essential \
        zip bzr curl libc6-dev libncurses5-dev:i386 x11proto-core-dev \
        libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
        libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos \
        python3-markdown libxml2-utils xsltproc zlib1g-dev:i386 schedtool \
        repo liblz4-tool bc lzop imagemagick libncurses5 rsync
    - mkdir halium
  get_source_script:
    - cd halium
    - git config --global user.name  "Artem Neizhmak"
    - git config --global user.email "ytartem0007@gmail.com"
    - repo init -u https://github.com/Halium/android -b halium-11.0 --depth=1
    - repo sync -c -j 16
    - cp ../xiaomi_rosy.xml halium/devices/manifests/
    - ./halium/devices/setup rosy
    - hybris-patches/apply-patches.sh --mb
  build_script:
    - cd halium
    - source build/envsetup.sh
    - breakfast rosy
    - ./halium/halium-boot/check-kernel-config kernel/xiaomi/rosy/arch/arm64/configs/rosy-perf_defconfig -w
    - cat /halium/device/xiaomi/rosy/BoardConfig.mk
    - echo "BOARD_KERNEL_CMDLINE += console=tty0" >> /halium/device/xiaomi/rosy/BoardConfig.mk
    - mka mkbootimg
    - export USE_HOST_LEX=yes
    - mka halium-boot
  env:
    GITHUB_TOKEN: ENCRYPTED[13a5662b449c90997bc914dc49c7c5fab2ed763cfdedda700cbb8372e4d8844e7b1a3044928d67888bcbb71aac0ad2f6]
  publish_release_script:
    - source ../publish_release.sh
